---
title: "Create maps using jpndistrict"
author: "Shinya Uryu"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: readable
vignette: >
  %\VignetteIndexEntry{Create maps using jpndistrict}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


```{r, echo = FALSE}
library(knitr)
opts_chunk$set(
  fig.argin = "center",
  fig.width = 7,
  fig.height = 5,
  warning = FALSE,
  message = FALSE
)
```

Loading data

```{r}
library(magrittr)
library(dplyr)
library(jpndistrict)
library(ggplot2)
library(ggthemes)
data("jpnprefs")
```

```{r, eval = TRUE}
spdf.33 <- spdf_jpn_cities(jis_code_pref = 33, jis_code = c(33101, 33102, 33103, 33104, 33205))
```

## ggplot2

```{r gg_jpn_district_pref33}
spdf_jpn_pref(code = 33, district = TRUE) %>% gg_jpn_district()
```


```{r gg_jpn_district_pref33_capital_point}
d33 <- jpnprefs %>% filter(prefecture == "岡山県") %>% 
               rename(lat = capital_latitude,
                      long = capital_longitude) %>% 
  mutate(id = 33101)

p <- spdf.33 %>% gg_jpn_district()
p + geom_point(data = d33, aes(x = long, y = lat, fill = "#2196F3", size = 6)) +
  guides(fill = FALSE, size = FALSE)
```

```{r gg_jpn_district_pref_feature_ggghost}
p <- spdf_jpn_cities(jis_code_pref = 33, jis_code = c(33103)) %>% gg_jpn_district()
p - theme_map()
```

## leaflet

```{r, eval = FALSE, echo = TRUE}
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addPolylines(data = spdf.33, color = "red")
```

## plotly (test)

```{r, eval = FALSE, echo = TRUE}
library(plotly)

g <- list(
  scope = "asia",
  showland = TRUE,
  landcolor = toRGB("grey83"),
  subunitcolor = toRGB("white"),
  countrycolor = toRGB("white"),
  showlakes = TRUE,
  lakecolor = toRGB("white"),
  showsubunits = TRUE,
  showcountries = TRUE,
  resolution = 50,
  projection = list(
    type = "conic conformal",
    rotation = list(lon = 130)
  ),
  lonaxis = list(
    showgrid = TRUE,
    gridwidth = 0.5,
    range = c(min(jpnprefs$capital_longitude) - 3, max(jpnprefs$capital_longitude) + 3),
    dtick = 5
  ),
  lataxis = list(
    showgrid = TRUE,
    gridwidth = 0.5,
    range = c(min(jpnprefs$capital_latitude) - 5, max(jpnprefs$capital_latitude) + 5),
    dtick = 5
  )
)

plot_geo(jpnprefs, lat = ~capital_latitude, lon = ~capital_longitude) %>%
  add_markers() %>%
  layout(geo = g)
```

```{r, eval = FALSE, echo = TRUE}
d <- read_ksj_p33(code = 33) %>%
  dplyr::filter(!grepl("(支所|出張所|庁舎)$", name))

g <- list(
  scope = "asia",
  showland = TRUE,
  landcolor = toRGB("grey83"),
  subunitcolor = toRGB("white"),
  countrycolor = toRGB("white"),
  showlakes = TRUE,
  lakecolor = toRGB("white"),
  showsubunits = TRUE,
  showcountries = TRUE,
  resolution = 50,
  projection = list(
    type = "conic conformal",
    rotation = list(lon = 130)
  ),
  lonaxis = list(
    showgrid = TRUE,
    gridwidth = 0.5,
    range = c(min(d$longitude) - 3, max(d$longitude) + 3),
    dtick = 5
  ),
  lataxis = list(
    showgrid = TRUE,
    gridwidth = 0.5,
    range = c(min(d$latitude) - 5, max(d$latitude) + 5),
    dtick = 5
  )
)

plot_geo(d@data, lat = ~latitude, lon = ~longitude) %>%
  add_markers(
    text = ~paste(d$name, "<br>", d$address), hoverinfo = "text"
  ) %>%
  layout(geo = g)
```

